;"DOORS.ZIL for Zork I: The Great Underground Empire"

<OBJECT BARROW-DOOR (IN STONE-BARROW)
    (ADJECTIVE HUGE STONE) (SYNONYM DOOR)
    (DESC "stone door")
    ;(ACTION BARROW-DOOR-FCN)
    (FLAGS DOORBIT NDESCBIT OPENBIT)>

<OBJECT	KITCHEN-WINDOW (IN LOCAL-GLOBALS)
    (ADJECTIVE KITCHEN SMALL) (SYNONYM WINDOW)
    (DESC "kitchen window")
    ;(ACTION KITCHEN-WINDOW-F)
    (FLAGS DOORBIT NDESCBIT)>
