"FIXTURES.ZIL for Zork I: The Great Underground Empire"

<OBJECT MAILBOX (IN WEST-OF-HOUSE)
	(ADJECTIVE SMALL) (SYNONYM MAILBOX BOX)
	(DESC "small mailbox")
	(CAPACITY 10)
    ;(ACTION MAILBOX-F)
	(FLAGS CONTBIT OPENABLEBIT)
>

